### ISSUE TITLE
Monitoring using the URL

### ISSUE THREAD

**Issue by uvzubovs** [cloudfoundry/healthcheck#1]
I see that the healthcheck has provision to monitor using HTTP GET to a URL. However, I don't believe Cloud Foundry is using it that way, or is it? If it is, how would I tell Cloud Foundry that my app needs to be monitored via the URL? Thanks!

**Comment by ematpl** [comment]
Hi, @uvzubovs, the CAPI team currently has a story in flight at https://www.pivotaltracker.com/story/show/134749805 to allow CF applications to specify an HTTP-based health check, which presumably would use the underlying HTTP functionality of this healthcheck binary. So I expect that feature will arrive soon in an upcoming CF final release (v249 or later).

Thanks,
Eric, CF Runtime Diego PM
