### ISSUE TITLE
HTTP check does not respect the timeout value, any URI that takes longer than 1 second to respond will never be marked healthy

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/healthcheck#5]
When setting an HTTP healthcheck with a custom timeout value, the HTTP check still uses a value of 1 second for the URI to respond, resulting in processes that have a long initial load time from never being marked as healthy.

To reproduce, push a simple PHP app with the following code:

    <html>
     <head>
      <title>PHP Test</title>
     </head>
     <body>
     <?php
     sleep(5);
     echo '<p>Hello World</p>';
     ?> 
     </body>
    </html>

Push it via CF with a custom timeout and HTTP check:

    cf push test01 -b php_buildpack -t 30 --no-start
    cf set-health-check test01 http --endpoint /
    cf start test01

The app will fail with the following errors:

    2017-09-26T18:36:21.28-0700 [CELL/0] ERR Failed to make HTTP request to '/' on port 8080: timed out after 1.00 seconds
    2017-09-26T18:36:21.28-0700 [CELL/0] ERR Timed out after 30s: health check never passed.

**Comment by emalm** [comment]
Hi, @amhuber,

That `-t` flag on `cf push` sets the `health_check_timeout` field on the (v2) app entity in CC, which in turn sets the deadline by which each app instance must become healthy after invoking its start command. That 30s value is visible in the second log-line you reported from the instance start failure. Looking through https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/diego/app_recipe_builder.rb, I don't think anything in CC lets an end-user set the timeout flag on each healthcheck invocation, which is the timeout you would want to control for this slower endpoint in your test app. @zrob might know if there are plans for CC to expose configuring that per-health-check timeout through either the v2 or the v3 CC API.

Thanks,
Eric, CF Diego PM

**Comment by amhuber** [comment]
Thanks for confirming, I wasn't able to find by looking through code if the "timeout" value passed all the way through to the HTTP check, which is how I expected it to work.  Instead of exposing the new value, is there any reason not to just set the HTTP check timeout to the start timeout?

**Comment by schulzh** [comment]
This issue is also affecting us.
When using the spring boot actuator, the health endpoint tests if it is able to establish a database connection. When an app is under load, this very quickly goes over 1 second, and cf kills a perfectly healthy instance.
Not being able to set this http endpoint timeout is a huge issue.

**Comment by emalm** [comment]
Hi, @schulzh, I suggest that you instead [open an issue on Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng/issues/new), as that component is responsible for setting the per-invocation request timeout on the healthcheck when it submits the app to Diego to run. The request timeout value is already configurable on the healthcheck executable, so there's nothing to change on this repository. 

@amhuber, sorry I missed your last question. Just as a one-second request timeout may be too short for the target endpoint, the instance start timeout, which defaults to 60 seconds but may be up to 3 minutes or more depending on Cloud Controller configuration, may be too long to be effective at detecting certain classes of failures.
