### ISSUE TITLE
CF health check default port issue

### ISSUE THREAD

**Issue by NagendraHegde** [cloudfoundry/healthcheck#6]
Hi All,

I have an issue regarding cloudfoundry health check feature.

Generally, when we set health check as http and specify an endpoint, CF will check the endpoint responses frequently to ensure the health of the application.
In docker based environment, it is by default the port that we expose. (As explained in this CF documentation: https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html)

In my use case,  I have an application, where there are two ports listening, (that is, in tomcat server xml, there are two connectors each for two different ports) as below:

        <Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000"  maxHttpHeaderSize="32768"/>
        <Connector port="8001" protocol="HTTP/1.1" connectionTimeout="20000"  maxHttpHeaderSize="32768" address="127.0.0.1"/>

(the above creates a connector at 8080 accessible by anyone, and another connector at 8001 access restricted to only localhost calls)

And in the docker file, I have exposed port 8080.

Now, when I launch the application, sometimes app crashes, failing health check at port 8001, and sometimes, app gets started with health check successfully done at port 8080.

Why CF is checking health endpoint at 8001, when the default exposed port 8080 is already present? And why it is randomly picking either 8001 or 8080 ports? Is this behavior seen before by anyone else? If yes, what is the solution to point to 8080 for health check? Please let me know.

Note: the health check endpoint in my app always returns 200 at both ports.

Thanks,
Nagendra

**Comment by sunjayBhatia** [comment]
@NagendraHegde this might be more of an issue with the `dockerapplifecycle` than the healthcheck code, but we can keep the issue here

Some questions we have to help diagnose this:
- What version of `diego-release` (and `cf-deployment`) is this occurring with?
- Can you provide a simple `Dockerfile` that reproduces the issue?
- Are you pushing the app with any additional port mappings, etc.?

**Comment by hsiliev** [comment]
Using cf-deployment v12.0.0.

The colleagues described the following scenario:
1. Push docker image with exposed port 8001
2. Add new connector on 8080, expose 8080 and restrict 8001 to 127.0.0.1
3. Push new docker image with exposed port 8080
4. Healthchecker still tries to reach 8001 

Perhaps this has more to do with `dockerapplifecycle` indeed as to me it seems the old port is just left from app metadata creation.

We'll try to reproduce with simple app, getting rid of all internal stuff get back to you.

**Comment by hsiliev** [comment]
Yep - we have rebuilt the image, replacing 8001 with 8080.

**Comment by heyjcollins** [comment]
@hsiliev - I'm going to close this issue with the assumption you and your colleagues haven't been able to reproduce the issue. If that's actually not the case, please feel free to comment and reopen.
